version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cp0_postgresDB
    restart: always
    environment:
      POSTGRES_USER: YOUR_USER
      POSTGRES_PASSWORD: YOUR_PASSWORD
      POSTGRES_DB: YOUR_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: cp0_backend
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/YOUR_DB
      SPRING_DATASOURCE_USERNAME: YOUR_USER
      SPRING_DATASOURCE_PASSWORD: YOUR_PASSWORD
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: cp0_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: YOUR_EMAIL
      PGADMIN_DEFAULT_PASSWORD: YOUR_PASSWORD
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata: