version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cp0_postgresDB
    restart: always
    environment:
      POSTGRES_USER: cp0
      POSTGRES_PASSWORD: cp0_Password
      POSTGRES_DB: cp0_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: cp0_backend
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cp0_DB
      SPRING_DATASOURCE_USERNAME: cp0
      SPRING_DATASOURCE_PASSWORD: cp0_Password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: cp0_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  pgdata: