services:
  backend:
    build: .
    container_name: cp0_backend_prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_SECURITY_ENABLED: true
    restart: always
    env_file:
      - .env.prod
    ports:
      - "8081:8080"   # attention au port pour Ã©viter conflit avec dev
    depends_on:
      - postgres